name: Jira PR Link and Delete Branch After Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  enforce-jira-link:
    runs-on: ubuntu-latest

    steps:
      - name: Check Jira link in PR description
        run: |
          pr_body=$(curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
                    jq -r '.body')
          if [[ ! $pr_body =~ KAN-[0-9]+ ]]; then
            echo "Jira task link not found in PR description."
            exit 1
          fi

  delete-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete branch on remote
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch --all
          if git rev-parse --quiet --verify ${{ github.event.pull_request.head.ref }}; then
            git push origin --delete ${{ github.event.pull_request.head.ref }}
          fi
